name: APK_Uretici
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python_Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerecleri_Yukle
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: APK_Olustur
        run: buildozer android debug

      - name: Dosyayi_Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: Uygulamaniz
          path: bin/*.apk
          
