name: APK_Yapici
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Buildozer_Calistir
        uses: Niklas05/buildozer-action@master
        with:
          command: buildozer android debug
          repository_display_name: Uygulamam
          
