name: APK_Uretici
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Buildozer_Aksiyonu
        uses: Niklas05/buildozer-action@v1
        with:
          command: buildozer android debug
      - name: APK_Yukle
        uses: actions/upload-artifact@v4
        with:
          name: Uygulamaniz
          path: bin/*.apk
          
